#:import Counter Widgets

<SettingsScreen>:
    BoxLayout:
        orientation: "vertical"
        Label:
            text: "Settings"
        Button:
            text: "Sync Orders"
            on_press: root.fetch_orders()
        Button:
            text: "Reset Database"
            on_press: root.reset_database()
        Button:
            text: "Generate Sample Data"
            on_press: root.generate_data()